spring.application.name=spring_thymeleaf

spring.datasource.url=jdbc:mysql://localhost:3306/radiologie?createDatabaseIfNotExist=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.initialization-fail-timeout=0
